# options for analysis running
run:
  # include test files or not, default is true
  tests: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
#    - exhaustive
#    - exhaustivestruct
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
#    - goerr113
#    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
#    - lll
    - makezero
    - misspell
    - nestif
    - noctx
    - prealloc
    - predeclared
    - scopelint
    - sqlclosecheck
    - stylecheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace


linters-settings:

  gosec:
    # all rules enabled
    # see also: https://securego.io/docs/rules/rule-intro.html
    config:
      global:
        # allow #nosec override comments
        nosec: enabled
        # disable potentially noisy stricter audit mode
        audit: disabled
      G101: # "Look for hard-coded credentials"
        mode: strict
