apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: glamplify
  description:  Go Amplify Module of useful common tools.
  links:
    - title: Github
      url: https://github.com/cultureamp/glamplify
  tags:
    - users-internal
    - camp-platform
    - data-none
  annotations:
    github.com/project-slug: cultureamp/glamplify
    github.com/team-slug: cultureamp/core-services
spec:
  type: library
  owner: core-services
  lifecycle: production
