app:
    name: "service-name"
    version: 1.0
  
    loggers:
        rules:
            -   name: "default"
                level: "warn"
                writeto:
                    -   target: "stderr-text"

            -   name: "detailed"
                level: "debug"
                writeto:
                    -   target: "stderr-text"

            -   name: "public"
                level: "info"
                writeto:
                    -   target: "stderr-text"
                    -   target: "splunk-json"
                    -   target: "slack-text"

        targets:
            stream:
                -   name: "stderr-text"
                    output: "stderr"
                    formatter: "text"
                    fullTimestamp: true

                -   name: "json-info"
                    output: "stderr"
                    formatter: "json"
                    fullTimestamp: true

            slack:
                -   name: "slack-text"
                    formatter: "text"
                    fullTimestamp: true
                    url: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"
                    channel: "#slack-test"
                    emoji: ":ghost:"

            splunk:
                -   name: "splunk-json"
                    formatter: "text"
                    fullTimestamp: true
                    url: "https://splunk/path"
                    token: "#####"
                    source: "source-location"
                    sourceType: "source-type"
                    index: "splunk-index"

