app:
    name: "service-name"
    version: 1.0
  
    streamloggers:
        -   name: default
            level: warn
            output: stderr
            formatter: text
            fullTimestamp: true

        -   name: json
            level: info
            output: stderr
            formatter: json
            fullTimestamp: true



