name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.15.5'

      - name: GOLangCI-Lint
        # https://golangci-lint.run/usage/configuration/  https://golangci-lint.run/usage/linters/
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.29.0
          golangci-lint run --tests=false --disable-all --enable=deadcode --enable=gosimple --enable=govet --enable=ineffassign --enable=staticcheck --enable=structcheck --enable=unused --enable=varcheck --enable=bodyclose --enable=depguard --enable=dogsled 
