name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.15.5'

      - name: GOLint
        run: |
          go get -u golang.org/x/lint/golint

          golint --set_exit_status ./...

      - name: GOLangCI-Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.29.0

          golangci-lint run --tests=false