name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.15.5'

      - name: GOLangCI-Lint
        # https://golangci-lint.run/usage/configuration/  https://golangci-lint.run/usage/linters/
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.29.0
          golangci-lint run --tests=false --disable-all -E=deadcode -E=gosimple -E=govet -E=ineffassign -E=staticcheck -E=structcheck -E=unused -E=varcheck -E=bodyclose -E=depguard -E=dogsled -E=dupl -E=errorlint -E=exhaustive -E=exhaustivestruct -E=exportloopref -E=funlen -E=gochecknoinits -E=gocognit -E=goconst
